### PR TITLE
fix: merge objects with `Module` type

### LINKED ISSUE #119: [Bug] Objects exported with '* as' export aren't merged recursively
### Environment

Operating System: Linux
Node Version: v18.18.0
Nuxt Version: 3.8.2
CLI Version: 3.10.0
Nitro Version: 2.8.1
Package Manager: npm@9.4.2
Builder: -
User Config: devtools, extends
Runtime Modules: -
Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-bcxfrv?file=README.md

### Describe the bug

merge app.config from different layers using namespace imports to combine different parts of the config, e.g:

```
import * as pages from './config/pages'

export default defineAppConfig({
  pages,
})
```

Check the console:

Expected:

`{ nuxt: { buildId: 'dev' }, pages: { foo: { nested: 1 }, bar: 2 } }`

Actual:

`{ nuxt: { buildId: 'dev' }, pages: { bar: 2 } }`

### Additional context

This is a regression that was introduced with 6.1.3 release, specifically with this PR https://github.com/unjs/defu/pull/111
@pi0 I'm quite dissapointed with the overall workflow this change was merged with. Test coverage was very small for such fundamental change, but even those tests that were written were [skipped](https://github.com/unjs/defu/pull/111/files#diff-e5de8f24089ff6aa7bf6aa409dcb5122ef2fc2b58bb1f0f36f7aaec5b3119954R53), there was no code review. Was it some kind of pre-holiday accident? 🥲 
IMO, any changes like this deserves at least minor (not a patch) and better - major version bump because it's a fundamental change to how objects are merged and this is a main goal of this lib.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by manniL**
### 🔗 Linked issue

Resolves #119 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist
- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/defu.ts [hunk 1]
```diff
@@ -57,8 +56,7 @@ function _isPlainObject(value: unknown): boolean {
     (prototype === null ||
       prototype === Object.prototype ||
       Object.getPrototypeOf(prototype) === null) &&
-    !(Symbol.toStringTag in value) &&
-    !(Symbol.iterator in value)
+    (!(Symbol.toStringTag in value) || !(Symbol.iterator in value))
```
Comment (pi0) [inline src/defu.ts:59]: I'm wondering if it is purely for Date merging fix, using `instance of Date` would be faster

Comment (manniL) [reply src/defu.ts:59]: it isn't. See the linked issue. It also applies to `Module` (import via *)

Comment (pi0) [reply src/defu.ts:59]: Oh, I see! With this PR want to merge Module instances!

Comment (pi0) [reply src/defu.ts:59]: Checking, this logic currently basically bypasses entire L59 as `iterator` symbol does not exist in any of tested values (removing the line also all the tests pass). Wondering how we can cover it

Comment (manniL) [reply src/defu.ts:59]: > Oh, I see! With this PR want to merge Module instances!

yes indeed 👍🏻

Comment (manniL) [reply src/defu.ts:59]: >  Checking, this logic currently basically bypasses entire L59 as iterator symbol does not exist in any of tested values (removing the line also all the tests pass). Wondering how we can cover it

Oh, I see 🤔 That's a bit tricky. I also wonder how to cover it then...

But - do we need to? Dates are correctly replaced (not merged) like that too

Comment (pi0) [reply src/defu.ts]: I have ported test suite of is-plain-object (see commits to main) and also merged in with this PR. Intrestingly we will be breaking two more tests at least (`Math` and native `arguments` will be wrongly detected as pure object)

Comment (pi0) [reply src/defu.ts]: Updated with a logic that precisely works for `Module` to reduce (more!) regression chances
